
var data = [
  {letter: "a", frequency: 0},
  {letter: "b", frequency: 0},
  {letter: "c", frequency: 0},
  {letter: "d", frequency: 0},
  {letter: 'e', frequency: 0},
  {letter: 'f', frequency: 0},
  {letter: 'g', frequency: 0},
  {letter: 'h', frequency: 0},
  {letter: 'i', frequency: 0},
  {letter: 'j', frequency: 0},
  {letter: 'k', frequency: 0},
  {letter: 'l', frequency: 0},
  {letter: 'm', frequency: 0},
  {letter: 'n', frequency: 0},
  {letter: 'o', frequency: 0},
  {letter: 'p', frequency: 0},
  {letter: 'q', frequency: 0},
  {letter: 'r', frequency: 0},
  {letter: 's', frequency: 0},
  {letter: 't', frequency: 0},
  {letter: 'u', frequency: 0},
  {letter: 'v', frequency: 0},
  {letter: 'w', frequency: 0},
  {letter: 'x', frequency: 0},
  {letter: 'y', frequency: 0},
  {letter: 'z', frequency: 0},
  {letter: 'other', frequency:0},
  {total_letters: 0}
];
